; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Only build the ESP32 environment during standard "Build" / pio run operations
[platformio]
default_envs = freenove_esp32_wrover

; esp32
[env:freenove_esp32_wrover]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11 -std=gnu++23
build_flags = -std=gnu++17

; testing
[env:native]
platform = native
test_framework = unity
test_build_src = true
build_src_filter =
    +<pwm/pwm_resource_manager.cpp>
    -<main.cpp>